name: Node.js CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Check linting
        run: npm run lint

      - name: Run the tests
        run: npm run test

      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Update branch remote
        run: git remote update

      - name: Fetch to new infos
        run: git fetch

      - name: Switch to main branch
        run: git checkout main

      - name: Rebase develop into main
        run: git pull --rebase origin develop

      - name: Push to main if tests pass
        if: success()
        run: git push origin main
